# Generated by Django 4.2.6 on 2023-10-21 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_user_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calculator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expression', models.CharField(max_length=999)),
                ('result', models.CharField(max_length=666)),
            ],
            options={
                'db_table': 'app_users',
            },
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
